name: "robertcboll"
description: ""
author: "robertcboll"

url: "http://localhost:4000"
#url: "http://robertcboll.com"

markdown: kramdown
highlighter: pygments

kramdown:
  input: GFM

exclude: [README.md, Rakefile]
paginate: 16
permalink: /:title
