name: "robertcboll"
description: ""
author: "robertcboll"

#url: "http://localhost:4000"
url: "http://robertcboll.com"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude: [README.md, Rakefile]
paginate: 16
permalink: /:title
